[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.74"
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = "0.4"
yew = "0.19.3"
yewtil = {version = "0.4", features = ["future"]}
patternfly-yew = "0.2.2"
graphql_client = "0.11.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
log = "0.4"
wasm-logger = "0.2.0"
web-sys = "0.3.51"
thiserror = "1.0.37"

[build-dependencies]
backend-impl = { path = "../backend-impl" }
anyhow = "1.0.66"