[package]
name = "backend-artifact"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
actix-web-static-files = "4.0"
static-files = "0.2.1"
backend-impl = { path = "../backend-impl" }
async-graphql = "4.0.16"
async-graphql-actix-web = "4.0.16"
env_logger = "0.9.3"
log = "0.4"
prometheus = "0.13.3"
actix-web-prometheus = { version = "0.1.2", features = ["process"] }
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
static-files = "0.2.1"