[package]
name = "backend-artifact"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4"
actix-web-static-files = "4.0"
static-files = "0.2.3"
backend-impl = { path = "../backend-impl" }
async-graphql = "6.0.10"
async-graphql-actix-web = "6.0.10"
env_logger = "0.10.0"
log = "0.4"
prometheus = "0.13.3"
actix-web-prometheus = { version = "0.1.2", features = ["process"] }
thiserror = "1.0.50"
actix-4-jwt-auth = "0.6.1"
biscuit = "0.6.0-beta1"
serde = "1.0.192"

[build-dependencies]
static-files = "0.2.3"