[package]
name = "backend-artifact"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-web-static-files = "4"
actix-service = "2.0.2"
static-files = "0.2.3"
backend-impl = { path = "../backend-impl" }
async-graphql = "6.0.11"
async-graphql-actix-web = "6.0.11"
env_logger = "0.10.0"
log = "0.4"
prometheus = "0.13.3"
actix-web-prometheus = { version = "0.1.2", features = ["process"] }
thiserror = "1.0.51"
actix-4-jwt-auth = { version = "1.1.0" }
tracing-actix-web = "0.7"
tracing = { version = "0.1", features = ["log"] }
serde = "1.0.193"
serde_json = "1.0.108"
futures-util = "0.3.29"

[build-dependencies]
static-files = "0.2.3"