[package]
name = "backend-impl"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "4.0.16"
lazy_static = "1.4.0"
serde = "1.0.147"
serde_yaml = "0.9.14"
serde_json = "1.0.88"
log = "0.4"
