name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy trunk
    - name: Build Backend
      run: cargo build -p backend-impl
    - name: Build Yew
      working-directory: yew-app
      run: trunk build
    - name: Build Backend
      run: cargo build -p backend-artifact
    - name: Run Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
