name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Backend
      run: cargo build -p backend-impl
    - name: Build Yes
      run: cd yew-app && trunk build
    - name: Build Binary
      run: cargo build -p backend-artifact
    - name: Run Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
